### ISSUE TITLE
InitError: Failed to initialize ReclaimProofRequest

### ISSUE THREAD

**Issue by Skandesh** [reclaimprotocol/reclaim-js-sdk#9]
Followed the steps as it is from README.md and got this error 

`Uncaught (in promise) InitError: Failed to initialize ReclaimProofRequest
    at _ReclaimProofRequest.<anonymous> (http://localhost:3002/static/js/bundle.js:6063:15)
    at Generator.throw (<anonymous>)
    at rejected (http://localhost:3002/static/js/bundle.js:5039:29)
Caused by: SignatureGeneratingError: Error generating signature for applicationSecret: mytopsecret
    at _ReclaimProofRequest.<anonymous> (http://localhost:3002/static/js/bundle.js:6236:15)
    at Generator.next (<anonymous>)
    at http://localhost:3002/static/js/bundle.js:5045:61
    at new Promise (<anonymous>)
    at __async (http://localhost:3002/static/js/bundle.js:5029:10)
    at _ReclaimProofRequest.generateSignature (http://localhost:3002/static/js/bundle.js:6222:12)
    at _ReclaimProofRequest.<anonymous> (http://localhost:3002/static/js/bundle.js:6055:54)
    at Generator.next (<anonymous>)
    at http://localhost:3002/static/js/bundle.js:5045:61
    at new Promise (<anonymous>)`

![image](https://github.com/user-attachments/assets/f778065e-95cf-451b-8afe-643d7fc300ce)

using node - v18.17.1
Operating system - windows 11
npm - 9.6.7

**Comment by Skandesh** [comment]
There was issue while copy pasting my app-secret. apologies for opening this kiddo issue.

would be better if shown appropriate error message.
